import { aquarevaneApp } from "./aquarevane.mjs";
export const site = {
  baseUrl: "https://studio501.fr",
  name: "Studio501",
  publisher: "Nanouk Candela",
  tradeName: "Studio501",
  legalForm: "Entrepreneur individuel",
  siren: "104 315 957",
  siret: "104 315 957 00019",
  register: "Registre national des entreprises (RNE)",
  activityCode: "5829C",
  activityLabel: "Édition de logiciels applicatifs",
  address: {
    street: "61 rue de Lyon",
    postalCode: "75012",
    city: "Paris",
    country: "France",
    countryCode: "FR",
  },
  country: "France",
  primaryEmail: "contact@studio501.fr",
  storeEmail: "studio501.dev@gmail.com",
  phone: null,
  vatNumber: null,
  mediator: null,
  host: {
    name: "GitHub Pages",
    company: "GitHub, Inc.",
    address: "88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, États-Unis",
    supportUrl: "https://support.github.com/",
  },
};

export const apps = [
  {
    slug: "decision-tree-studio",
    name: "Decision Tree Studio",
    platform: "Windows",
    platformKey: "windows",
    status: "published",
    statusLabel: { fr: "Disponible sur Microsoft Store", en: "Available on Microsoft Store" },
    storeLabel: { fr: "Voir sur Microsoft Store", en: "View on Microsoft Store" },
    storeUrl: "https://apps.microsoft.com/detail/9PGPZ8W0TW2D?hl=fr-fr&gl=FR",
    icon: "/assets/apps/decision-tree/icon.png",
    screenshots: Array.from({ length: 6 }, (_, index) => `/assets/apps/decision-tree/screen-${index + 1}.jpg`),
    accent: "violet",
    summary: {
      fr: "Transformez vos procédures en arbres de décision, guides de diagnostic et parcours interactifs clairs.",
      en: "Turn procedures into clear decision trees, diagnostic guides and interactive journeys.",
    },
    description: {
      fr: [
        "Decision Tree Studio transforme les procédures complexes en parcours visuels faciles à créer et simples à suivre.",
        "Pensé pour le support, la formation, le dépannage et les procédures internes, il réunit l’édition et la présentation dans une interface claire.",
      ],
      en: [
        "Decision Tree Studio turns complex procedures into visual journeys that are easy to create and follow.",
        "Designed for support, training, troubleshooting and internal procedures, it brings editing and presentation together in a clear interface.",
      ],
    },
    features: {
      fr: ["Éditeur visuel avec cartes et connexions", "Questions, choix, résultats et cartes libres", "Projets réunissant plusieurs arbres", "Images, liens et fichiers intégrés", "Mode Présentation guidé", "Import et sauvegarde JSON", "Export HTML responsive", "Interface française et anglaise, réglable jusqu’aux écrans 4K"],
      en: ["Visual editor with cards and connections", "Questions, choices, results and free-form cards", "Projects containing multiple trees", "Embedded images, links and files", "Guided Presentation mode", "JSON import and backup", "Responsive HTML export", "French and English interface scalable for 4K displays"],
    },
    privacyLead: {
      fr: "Les projets restent sur l’appareil, sauf export ou partage déclenché par l’utilisateur. Aucun compte ni publicité.",
      en: "Projects remain on the device unless the user exports or shares them. No account and no advertising.",
    },
  },
  {
    slug: "universal-converter",
    privacySlug: "universal-converter-studio",
    name: "Universal Converter Studio",
    platform: "Windows",
    platformKey: "windows",
    status: "published",
    statusLabel: { fr: "Disponible sur Microsoft Store", en: "Available on Microsoft Store" },
    storeLabel: { fr: "Voir sur Microsoft Store", en: "View on Microsoft Store" },
    storeUrl: "https://apps.microsoft.com/detail/9NBR4F51XP7N?hl=fr-fr&gl=FR",
    icon: "/assets/apps/universal-converter/icon.png",
    screenshots: [],
    accent: "cyan",
    monogram: "UC",
    summary: {
      fr: "Convertissez vidéos, images, fichiers audio et CD audio directement sur votre PC.",
      en: "Convert video, images, audio files and audio CDs directly on your PC.",
    },
    description: {
      fr: [
        "Universal Converter Studio regroupe les conversions vidéo, image et audio dans une interface cohérente pour Windows 10 et 11.",
        "Un fichier, un dossier ou un lot peut être traité localement. L’import de CD audio prend en charge MP3, FLAC et WAV.",
      ],
      en: [
        "Universal Converter Studio brings video, image and audio conversion together in one consistent interface for Windows 10 and 11.",
        "A file, a folder or a batch can be processed locally. Audio CD import supports MP3, FLAC and WAV.",
      ],
    },
    features: {
      fr: ["Conversion vidéo, image et audio", "Traitement d’un fichier, d’un dossier ou par lots", "Import de CD audio", "File d’attente et historique locaux", "Moteur FFmpeg exécuté sur le PC", "Aucun compte", "Aucun abonnement", "Aucun envoi des médias vers un serveur de conversion"],
      en: ["Video, image and audio conversion", "Single-file, folder and batch processing", "Audio CD import", "Local queue and history", "FFmpeg engine running on the PC", "No account", "No subscription", "No media upload to a conversion server"],
    },
    privacyLead: {
      fr: "Les médias et l’historique de conversion restent sur le PC. Aucun compte, publicité ou analyse d’usage.",
      en: "Media and conversion history remain on the PC. No account, advertising or usage analytics.",
    },
  },
  {
    slug: "ma-liste-de-courses",
    name: "Ma Liste de Courses",
    platform: "Android",
    platformKey: "android",
    status: "published",
    statusLabel: { fr: "Disponible sur Google Play", en: "Available on Google Play" },
    storeLabel: { fr: "Disponible sur Google Play", en: "Get it on Google Play" },
    storeUrl: "https://play.google.com/store/apps/details?id=com.nanouk.digitalshoppinglist",
    packageName: "com.nanouk.digitalshoppinglist",
    icon: "/assets/apps/shopping-list/icon.webp",
    screenshots: Array.from({ length: 6 }, (_, index) => `/assets/apps/shopping-list/screen-${index + 1}.webp`),
    screenshotAspect: "portrait",
    accent: "mint",
    summary: {
      fr: "Une liste de courses premium, rapide, claire et 100 % locale, sans publicité ni abonnement.",
      en: "A fast, clear and fully local premium shopping list with no ads or subscription.",
    },
    description: {
      fr: [
        "Préparez vos courses simplement avec plusieurs listes, l’ajout rapide, les quantités et un classement automatique par catégories.",
        "Plus de 1 400 produits et variantes sont reconnus. Vous pouvez corriger une catégorie ou une icône, puis l’application mémorise votre choix.",
      ],
      en: [
        "Prepare your shopping simply with multiple lists, quick entry, quantities and automatic category sorting.",
        "More than 1,400 products and variants are recognised. You can correct a category or icon and the app remembers your choice.",
      ],
    },
    features: {
      fr: ["Achat unique, sans abonnement", "Aucune publicité et aucun compte obligatoire", "Plusieurs listes et ajout rapide avec quantités", "Plus de 1 400 produits et variantes reconnus", "Classement par catégories et correction manuelle", "Mémorisation des choix", "Partage et import de listes", "Sauvegarde et restauration complètes", "Thèmes, français et anglais"],
      en: ["One-time purchase, no subscription", "No ads and no mandatory account", "Multiple lists and quick entry with quantities", "More than 1,400 recognised products and variants", "Category sorting with manual correction", "Choice memory", "List sharing and import", "Complete backup and restore", "Themes, French and English"],
    },
    privacyLead: {
      fr: "Les listes restent sur l’appareil. Un fichier ne quitte l’application que lorsque l’utilisateur choisit de le partager ou l’exporter.",
      en: "Lists remain on the device. A file leaves the app only when the user chooses to share or export it.",
    },
  },
  {
    slug: "budget-assistant",
    name: "Budget Assistant",
    platform: "Android",
    platformKey: "android",
    status: "published",
    statusLabel: { fr: "Disponible sur Google Play", en: "Available on Google Play" },
    storeLabel: { fr: "Disponible sur Google Play", en: "Get it on Google Play" },
    storeUrl: "https://play.google.com/store/apps/details?id=com.nanouk.widgetbudgetminute",
    packageName: "com.nanouk.widgetbudgetminute",
    icon: "/assets/apps/budget-assistant/icon.webp",
    screenshots: Array.from({ length: 6 }, (_, index) => `/assets/apps/budget-assistant/screen-${index + 1}.webp`),
    screenshotAspect: "portrait",
    accent: "coral",
    summary: {
      fr: "Suivez dépenses, budgets et charges fixes sans compte, publicité ni connexion bancaire.",
      en: "Track expenses, budgets and fixed costs with no account, ads or bank connection.",
    },
    description: {
      fr: [
        "Budget Assistant aide à comprendre rapidement ce qu’il reste à dépenser sur le jour, la semaine ou le mois.",
        "Ajoutez vos dépenses et entrées positives, suivez les charges récurrentes, consultez l’historique et gardez une synthèse dans un rapport PDF.",
      ],
      en: [
        "Budget Assistant helps you quickly understand what remains to spend for the day, week or month.",
        "Add expenses and positive entries, follow recurring costs, review history and keep a clear PDF summary.",
      ],
    },
    features: {
      fr: ["Achat unique, sans abonnement", "Suivi par jour, semaine et mois", "Budget mensuel et calcul du restant", "Dépenses, entrées positives et catégories", "Charges fixes et dépenses récurrentes", "Historique complet", "Widget Android", "Rapports PDF mensuels", "Sauvegarde et restauration", "Fonctionnement local, sans connexion bancaire"],
      en: ["One-time purchase, no subscription", "Daily, weekly and monthly tracking", "Monthly budget and remaining balance", "Expenses, positive entries and categories", "Fixed and recurring costs", "Complete history", "Android widget", "Monthly PDF reports", "Backup and restore", "Local operation with no bank connection"],
    },
    privacyLead: {
      fr: "Les données budgétaires sont stockées localement et ne sont pas envoyées à un serveur Studio501.",
      en: "Budget data is stored locally and is not sent to a Studio501 server.",
    },
  },
  {
    slug: "widget-pilulier",
    name: "Widget Pilulier",
    platform: "Android",
    platformKey: "android",
    status: "published",
    statusLabel: { fr: "Disponible sur Google Play", en: "Available on Google Play" },
    storeLabel: { fr: "Disponible sur Google Play", en: "Get it on Google Play" },
    storeUrl: "https://play.google.com/store/apps/details?id=com.nanouk.widgetpilulier",
    packageName: "com.nanouk.widgetpilulier",
    icon: "/assets/apps/widget-pilulier/icon.webp",
    screenshots: {
      fr: Array.from({ length: 6 }, (_, index) => `/assets/apps/widget-pilulier/fr/screen-${index + 1}.webp`),
      en: Array.from({ length: 6 }, (_, index) => `/assets/apps/widget-pilulier/en/screen-${index + 1}.webp`),
    },
    screenshotAspect: "portrait",
    accent: "gold",
    summary: {
      fr: "Planifiez vos prises et gardez-les visibles sur votre écran d’accueil.",
      en: "Plan your doses and keep them visible on your home screen.",
    },
    description: {
      fr: [
        "Widget Pilulier vous aide à organiser vos médicaments, vitamines et compléments au quotidien. Planifiez les horaires de prise, recevez des rappels locaux et consultez les prises du jour depuis l’application ou le widget Android.",
        "L’application fonctionne sans compte, sans publicité et sans serveur applicatif. Vos traitements, horaires, historiques et préférences restent sous votre contrôle, sur votre appareil.",
      ],
      en: [
        "Widget Pilulier helps you organize medications, vitamins, and supplements day by day. Schedule dose times, receive local reminders, and view today’s intakes in the app or on the Android home screen widget.",
        "The app works without an account, ads, or an app server. Your treatments, schedules, history, and preferences remain under your control, on your device.",
      ],
    },
    features: {
      fr: ["Achat unique, sans abonnement", "Prises du jour regroupées par moment", "Actions Pris, Ignorer et suivi des prises manquées", "Widget Android personnalisable en plusieurs tailles", "Action Pris directement depuis le widget", "Rappels locaux et rappel tardif configurable", "Horaires et fréquences flexibles", "Pause temporaire d’un traitement", "Historique et statistiques simples", "Sauvegarde et restauration JSON locales", "Thèmes clair et sombre, français et anglais"],
      en: ["One-time purchase, no subscription", "Today’s intakes grouped by time of day", "Taken and Skip actions with missed-dose tracking", "Customizable Android widget in multiple sizes", "Mark a dose as Taken directly from the widget", "Local reminders and an optional late reminder", "Flexible times and frequencies", "Temporarily pause a treatment", "Local history and simple statistics", "Local JSON backup and restore", "Light and dark themes, English and French"],
    },
    privacyLead: {
      fr: "Les traitements, horaires, historiques et préférences restent sur l’appareil. Aucun compte, publicité ni serveur applicatif.",
      en: "Treatments, schedules, history and preferences remain on the device. No account, ads or app server.",
    },
  },
  {
    slug: "myhomeassistant",
    name: "MyHomeAssistant",
    platform: "Android",
    platformKey: "android",
    status: "published",
    statusLabel: { fr: "Disponible sur Google Play", en: "Available on Google Play" },
    storeLabel: { fr: "Disponible sur Google Play", en: "Get it on Google Play" },
    storeUrl: "https://play.google.com/store/apps/details?id=com.nanouk.myhomeassistant",
    packageName: "com.nanouk.myhomeassistant",
    icon: "/assets/apps/myhomeassistant/icon.webp",
    screenshots: Array.from({ length: 6 }, (_, index) => `/assets/apps/myhomeassistant/screen-${index + 1}.webp`),
    screenshotAspect: "portrait",
    accent: "gold",
    summary: {
      fr: "Organisez l’entretien de votre maison avec équipements, tâches, rappels locaux et widget.",
      en: "Organise home maintenance with equipment, tasks, local reminders and a widget.",
    },
    description: {
      fr: [
        "MyHomeAssistant vous aide à suivre les petites tâches importantes liées à la maison, au jardin et à vos équipements.",
        "Créez des tâches périodiques ou uniques, utilisez des modèles et visualisez clairement ce qui est en retard, proche ou prévu plus tard.",
      ],
      en: [
        "MyHomeAssistant helps you follow important recurring tasks for your home, garden and equipment.",
        "Create recurring or one-off tasks, use templates and clearly see what is overdue, coming soon or planned later.",
      ],
    },
    features: {
      fr: ["Équipements personnalisés", "Tâches périodiques et tâches uniques", "Modèles préremplis et checklists modifiables", "Priorités : en retard, sous 7 jours ou plus tard", "Historique des actions", "Rappels et notifications locales", "Widget Android", "Sauvegarde et restauration locales", "Modes clair et sombre, français et anglais"],
      en: ["Custom equipment", "Recurring and one-off tasks", "Ready-made templates and editable checklists", "Overdue, next 7 days and later priorities", "Action history", "Local reminders and notifications", "Android widget", "Local backup and restore", "Light and dark modes, French and English"],
    },
    privacyLead: {
      fr: "Les équipements, tâches et préférences restent sur l’appareil, sauf export ou partage volontaire.",
      en: "Equipment, tasks and preferences remain on the device unless voluntarily exported or shared.",
    },
  },
  {
    slug: "memoa",
    name: "Memoa",
    platform: "Android",
    platformKey: "android",
    status: "published",
    statusLabel: { fr: "Disponible sur Google Play", en: "Available on Google Play" },
    storeLabel: { fr: "Disponible sur Google Play", en: "Get it on Google Play" },
    storeUrl: "https://play.google.com/store/apps/details?id=com.nanouk.widgetanniversairesdates",
    packageName: "com.nanouk.widgetanniversairesdates",
    icon: "/assets/apps/memoa/icon.png",
    screenshots: [],
    accent: "gold",
    summary: {
      fr: "Anniversaires et dates importantes, visibles sur votre écran d’accueil.",
      en: "Birthdays and important dates, right on your Android home screen.",
    },
    description: {
      fr: [
        "Les belles attentions commencent par une date que l’on n’oublie pas.",
        "Memoa réunit vos anniversaires, rendez-vous, échéances et événements personnels dans une application claire, pensée autour d’un widget Android élégant. Consultez ce qui arrive, organisez vos proches et gardez vos prochaines dates visibles depuis l’écran d’accueil.",
      ],
      en: [
        "Thoughtful moments start with a date you remember.",
        "Memoa brings birthdays, appointments, deadlines, and personal events together in a clear app built around an elegant Android widget. See what’s coming up, organize the people who matter, and keep your next dates visible from your home screen.",
      ],
    },
    features: {
      fr: ["Achat unique, sans abonnement ni achat intégré", "Anniversaires et autres dates importantes", "Récurrence annuelle ou événement ponctuel", "Personnes et photos locales facultatives", "Catégories intégrées ou personnalisées", "Compte à rebours avant chaque événement", "Vue calendrier mensuelle", "Rappels locaux à l’heure choisie", "Widget redimensionnable", "Contenu et couleurs du widget personnalisables", "Thèmes clair, sombre ou système", "Export et import des données principales au format JSON", "Français et anglais"],
      en: ["One-time purchase with no subscription or in-app purchase", "Birthdays and other important dates", "Yearly recurrence or one-time events", "People and optional locally stored photos", "Built-in or custom categories", "Days remaining before each event", "Monthly calendar view", "Local reminders at the chosen time", "Resizable home-screen widget", "Customisable widget content and colours", "Light, dark or system theme", "JSON export and import for main data", "English and French"],
    },
    privacyLead: {
      fr: "Les événements, personnes, notes et photos restent dans l’espace privé de l’application sur votre appareil.",
      en: "Events, people, notes and photos remain in the app’s private storage on your device.",
    },
  },
  {
    slug: "arcade-501",
    name: "Arcade 501",
    platform: "Android",
    platformKey: "android",
    status: "preparing",
    statusLabel: { fr: "Publication en préparation", en: "Preparing for release" },
    packageName: "com.studio501.offlinearcade",
    icon: "/assets/apps/arcade-501/icon.png",
    screenshots: [],
    screenshotAspect: "portrait",
    accent: "cyan",
    summary: {
      fr: "Dix-huit jeux d’arcade et de réflexion entièrement hors ligne, sans publicité ni compte.",
      en: "Eighteen arcade and puzzle games that work fully offline, with no ads or account.",
    },
    description: {
      fr: [
        "Arcade 501 réunit 18 jeux tactiles : campagnes, défis infinis, matchs locaux et Mission 501.",
        "Les profils, scores, records et succès restent sur l’appareil. L’application fonctionne en mode avion, sans publicité ni connexion.",
      ],
      en: [
        "Arcade 501 brings together 18 touch games: campaigns, endless challenges, local matches, and Mission 501.",
        "Profiles, scores, records, and achievements remain on the device. The app works in airplane mode, with no ads or connection required.",
      ],
    },
    features: {
      fr: ["18 jeux jouables hors ligne", "594 niveaux de campagne", "Défis infinis et matchs locaux", "Modes solo et deux joueurs selon les jeux", "Mission 501", "Six profils locaux aux records séparés", "Français et anglais", "Aucune publicité, aucun compte et aucune connexion requise"],
      en: ["18 games playable offline", "594 campaign levels", "Endless challenges and local matches", "Solo and two-player modes depending on the game", "Mission 501", "Six local profiles with separate records", "English and French", "No ads, account, or connection required"],
    },
    privacyLead: {
      fr: "Les profils, scores, records et réglages restent sur l’appareil. Aucun compte, publicité ni transfert de données de jeu.",
      en: "Profiles, scores, records, and settings remain on the device. No account, ads, or gameplay-data transfer.",
    },
  },
  {
    slug: "trip-pocket",
    name: "Trip Pocket",
    platform: "Android",
    platformKey: "android",
    status: "preparing",
    statusLabel: { fr: "Publication en préparation", en: "Preparing for release" },
    packageName: "com.studio501.trippocket",
    icon: "/assets/apps/trip-pocket/icon.png",
    screenshots: Array.from({ length: 6 }, (_, index) => `/assets/apps/trip-pocket/screen-${index + 1}.webp`),
    screenshotAspect: "portrait",
    accent: "coral",
    summary: {
      fr: "Planning, réservations, documents, valise et budget réunis dans un carnet de voyage privé, même hors connexion.",
      en: "Itinerary, bookings, documents, packing and budget together in one private travel journal, even offline.",
    },
    description: {
      fr: [
        "Trip Pocket rassemble chaque étape utile dans un carnet de voyage privé et agréable à consulter.",
        "Préparez plusieurs voyages, organisez les journées, gardez vos réservations à portée de main et suivez votre budget sans créer de compte.",
      ],
      en: [
        "Trip Pocket brings every useful part of a trip together in a private travel journal designed to be easy to revisit.",
        "Plan several trips, organise each day, keep bookings close at hand and follow your budget without creating an account.",
      ],
    },
    features: {
      fr: ["Planning quotidien clair", "Réservations et documents conservés sur l’appareil", "Listes de valise et préparation avant le départ", "Budget, catégories, devises et taux personnalisés", "Export PDF, CSV et calendrier ICS", "Sauvegardes chiffrables par mot de passe", "Rappels locaux", "Aucun compte, publicité ni suivi d’usage", "Fonctionnement hors connexion"],
      en: ["Clear daily itinerary", "Bookings and documents kept on the device", "Packing lists and pre-departure preparation", "Budget, categories, currencies and custom rates", "PDF, CSV and ICS calendar exports", "Password-encryptable backups", "Local reminders", "No account, ads or usage tracking", "Offline operation"],
    },
    privacyLead: {
      fr: "Les voyages, documents, budgets et listes restent dans le stockage privé de l’application, sauf export ou partage choisi par l’utilisateur.",
      en: "Trips, documents, budgets and lists remain in private app storage unless the user chooses to export or share them.",
    },
  },
  {
    slug: "ma-voiture",
    name: "Ma Voiture",
    platform: "Android",
    platformKey: "android",
    status: "preparing",
    statusLabel: { fr: "Publication en préparation", en: "Preparing for release" },
    packageName: "com.studio501.mavoiture",
    icon: "/assets/apps/ma-voiture/icon.png",
    screenshots: ["garage", "maintenance", "fuel-charging", "documents"].map((name) => `/assets/apps/ma-voiture/${name}.png`),
    screenshotAspect: "portrait",
    accent: "cyan",
    summary: {
      fr: "Entretien, kilométrage, pleins, recharges, dépenses et documents dans un carnet privé pour vos véhicules.",
      en: "Maintenance, mileage, fuel, charging, costs and documents in a private logbook for your vehicles.",
    },
    description: {
      fr: ["Ma Voiture rassemble l’historique de vos véhicules dans un carnet utilisable hors connexion. Gérez votre garage, suivez les échéances et retrouvez vos documents sur votre appareil.", "Sans compte Studio501 ni publicité. Les mises à jour proposées à l’ouverture passent par Google Play ; les données du carnet restent locales.", "Les intervalles d’entretien sont des exemples modifiables : vérifiez les échéances auprès du constructeur ou d’un professionnel. Une copie numérique ne remplace pas nécessairement un document original."],
      en: ["Ma Voiture (My Car) brings your vehicles’ history together in an offline logbook. Manage your garage, track due dates and keep documents on your device.", "No Studio501 account or ads. Update offers at launch use Google Play; logbook data remains local.", "Suggested maintenance intervals are editable examples: confirm deadlines with the manufacturer or a professional. A digital copy may not replace an original document."],
    },
    features: {
      fr: ["Garage multi-véhicules, recherche et archives", "Photo du véhicule et galerie intégrée", "Entretiens, factures et historique du compteur", "Échéances par date et kilométrage", "Pleins, recharges et suivi de consommation", "Dépenses et totaux séparés par devise", "Documents et images dans un espace privé", "Suivi des pneus et rappels locaux", "Dossier de revente PDF et exports CSV", "Sauvegarde locale avec mot de passe facultatif", "Restauration par fusion ou remplacement", "Français et anglais, sans publicité"],
      en: ["Multi-vehicle garage, search and archives", "Vehicle photo and built-in gallery", "Maintenance, invoices and odometer history", "Due dates based on time and mileage", "Fuel, charging and consumption tracking", "Costs and totals separated by currency", "Documents and images in private storage", "Tyre tracking and local reminders", "Resale PDF report and CSV exports", "Local backup with optional password protection", "Merge or replace restore", "French and English, no ads"],
    },
    privacyLead: {
      fr: "Les véhicules, photos, documents et coûts restent sur l’appareil, sauf export ou partage choisi. Google Play gère séparément les mises à jour de l’application.",
      en: "Vehicles, photos, documents and costs stay on the device unless you choose to export or share them. Google Play handles app updates separately.",
    },
  },
  {
    slug: "mes-abonnements",
    name: "Mes Abonnements",
    platform: "Android",
    platformKey: "android",
    status: "preparing",
    statusLabel: { fr: "Publication en préparation", en: "Preparing for release" },
    packageName: "com.studio501.mesabonnements",
    icon: "/assets/apps/mes-abonnements/icon.png",
    screenshots: ["home", "subscription-detail", "timeline", "analytics"].map((name) => `/assets/apps/mes-abonnements/${name}.png`),
    screenshotAspect: "portrait",
    accent: "violet",
    summary: {
      fr: "Suivez manuellement vos abonnements, budgets, échéances et essais dans un carnet local avec rappels.",
      en: "Manually track subscriptions, budgets, due dates and trials in a local logbook with reminders.",
    },
    description: {
      fr: ["Mes Abonnements réunit vos dépenses récurrentes, prochaines échéances et essais dans un tableau de bord clair. Les projections et analyses reposent sur les informations que vous saisissez.", "L’application ne se connecte ni à votre banque ni aux fournisseurs et ne résilie rien à votre place. Elle fonctionne sans compte ni publicité, avec des données locales et des mises à jour proposées via Google Play."],
      en: ["Mes Abonnements (My Subscriptions) brings recurring costs, upcoming payments and trials into one clear dashboard. Projections and insights use the information you enter.", "The app does not connect to your bank or providers and does not cancel services for you. It works without an account or ads, with local data and update offers through Google Play."],
    },
    features: {
      fr: ["Saisie manuelle des abonnements et budgets", "Échéances, calendrier et projection sur douze mois", "Récurrences flexibles et suivi des essais", "Historique des prix et répartition par catégorie", "Devises et taux de conversion manuels datés", "Rappels avant renouvellement ou résiliation", "Widget Android et masquage des montants", "Documents facultatifs conservés localement", "Exports CSV et synthèses PDF", "Sauvegarde protégée par mot de passe facultatif", "Restauration par fusion ou remplacement", "Français et anglais, sans publicité"],
      en: ["Manual subscription and budget entry", "Due dates, calendar and twelve-month projection", "Flexible recurrence and trial tracking", "Price history and category breakdown", "Currencies and dated manual exchange rates", "Reminders before renewal or cancellation", "Android widget and hidden-amount privacy mode", "Optional documents stored locally", "CSV exports and PDF summaries", "Optional password-protected backup", "Merge or replace restore", "French and English, no ads"],
    },
    privacyLead: {
      fr: "Les abonnements, montants et documents restent sur l’appareil, sauf export ou partage choisi. Google Play traite séparément les informations techniques des mises à jour.",
      en: "Subscriptions, amounts and documents stay on the device unless you choose to export or share them. Google Play separately processes technical update information.",
    },
  },
  aquarevaneApp,
];

export const findApp = (slug) => apps.find((app) => app.slug === slug || app.privacySlug === slug);
