export const policies = {
  "decision-tree-studio": {
    lastUpdated: { fr: "26 juillet 2026", en: "July 26, 2026" },
    summary: {
      fr: "Decision Tree Studio fonctionne localement. Aucun compte, aucune publicité et aucune collecte des projets créés dans l’application.",
      en: "Decision Tree Studio works locally. No account, no advertising and no collection of projects created in the app.",
    },
    sections: {
      fr: [
        { title: "Responsable et portée", paragraphs: ["Cette politique concerne Decision Tree Studio pour Windows, édité par Candela — Studio501, France.", "Pour toute question relative à la confidentialité ou au support, vous pouvez écrire à studio501.dev@gmail.com ou contact@studio501.fr."] },
        { title: "Données personnelles", paragraphs: ["Decision Tree Studio ne nécessite pas de compte utilisateur. Studio501 ne collecte pas les projets, arbres de décision, contenus ou fichiers créés dans l’application."] },
        { title: "Fonctionnement local", paragraphs: ["Les projets créés dans l’application restent sur l’appareil, sauf lorsque l’utilisateur choisit lui-même de les exporter ou de les partager."] },
        { title: "Télémétrie et publicité", paragraphs: ["Decision Tree Studio n’intègre pas de publicité et n’est pas conçu pour transmettre à Studio501 des données d’utilisation ou de télémétrie personnalisée."] },
        { title: "Stockage, sauvegardes et suppression", paragraphs: ["Les données et sauvegardes sont stockées localement. L’utilisateur contrôle ses exports et sauvegardes externes. Les données privées de l’application peuvent être supprimées en supprimant les projets ou en désinstallant l’application selon le fonctionnement de Windows."] },
        { title: "Support", paragraphs: ["Les informations envoyées volontairement par e-mail sont utilisées uniquement pour répondre à la demande et assurer son suivi. Elles ne sont ni vendues ni utilisées à des fins publicitaires."] },
      ],
      en: [
        { title: "Controller and scope", paragraphs: ["This policy applies to Decision Tree Studio for Windows, published by Candela — Studio501, France.", "For privacy or support questions, contact studio501.dev@gmail.com or contact@studio501.fr."] },
        { title: "Personal data", paragraphs: ["Decision Tree Studio does not require a user account. Studio501 does not collect projects, decision trees, content or files created in the app."] },
        { title: "Local operation", paragraphs: ["Projects remain on the device unless the user explicitly chooses to export or share them."] },
        { title: "Telemetry and advertising", paragraphs: ["Decision Tree Studio contains no advertising and is not designed to send personalised usage or telemetry data to Studio501."] },
        { title: "Storage, backups and deletion", paragraphs: ["App data and backups are stored locally. Users control their external exports and backups. Private app data can be removed by deleting projects or uninstalling the app according to Windows behaviour."] },
        { title: "Support", paragraphs: ["Information voluntarily provided by email is used only to respond and follow up on the request. It is not sold or used for advertising."] },
      ],
    },
  },
  "universal-converter-studio": {
    lastUpdated: { fr: "1er août 2026", en: "August 1, 2026" },
    summary: {
      fr: "Les médias sont convertis directement sur le PC. Aucun compte, publicité ou service d’analyse d’usage ; aucun média n’est transmis à Studio501.",
      en: "Media is converted directly on the PC. No account, ads or usage analytics; no media is transmitted to Studio501.",
    },
    sections: {
      fr: [
        { title: "Responsable et portée", paragraphs: ["Éditeur et responsable des éventuelles données de support : Candela — Studio501, France.", "Contact : contact@studio501.fr. Cette politique concerne exclusivement Universal Converter Studio pour Windows."] },
        { title: "Informations traitées par l’application", paragraphs: ["Pour exécuter une conversion demandée, l’application peut lire localement les fichiers, dossiers et pistes de CD audio explicitement sélectionnés, leurs propriétés techniques et les réglages nécessaires."], bullets: ["contenu, noms, chemins, formats, codecs, dimensions, durée et taille des fichiers sélectionnés ;", "CD-Text disponible et titres, album ou artiste saisis pour l’import audio ;", "réglages de conversion, dossier de destination, état de la file et historique ;", "journal de diagnostic limité pouvant contenir des horodatages, versions de Windows et du runtime, chemins et messages d’erreur."] },
        { title: "Collecte, transmission et partage", paragraphs: ["L’application ne transmet aucune donnée à Studio501, à un serveur de conversion, à un annonceur ou à un service d’analyse.", "Elle ne crée aucun profil et ne contient pas de fonction intégrée de publication. Une transmission ne se produit que si l’utilisateur choisit lui-même d’envoyer un fichier par un autre logiciel ou de contacter le support."] },
        { title: "Stockage, conservation et suppression", paragraphs: ["Les originaux et résultats restent dans les emplacements choisis. Les préférences, la file, l’historique et les diagnostics sont stockés localement dans l’espace de l’application."], bullets: ["l’historique, les travaux terminés et les diagnostics peuvent être effacés depuis l’application ;", "la désinstallation supprime les données privées selon le fonctionnement de Windows ;", "les originaux et résultats conservés dans les dossiers personnels ne sont pas supprimés par ces commandes."] },
        { title: "Sécurité", paragraphs: ["Les traitements restent sur le PC et bénéficient des protections du compte utilisateur, du système de fichiers et de Windows. L’utilisateur reste responsable de la protection de son appareil, de ses sauvegardes et des dossiers choisis."] },
        { title: "Composants tiers", paragraphs: ["FFmpeg et ffprobe sont inclus avec l’application et exécutés localement pour analyser et convertir les médias. Aucun moteur de conversion n’est téléchargé pendant l’utilisation et aucun fichier n’est envoyé à ces composants via un service distant."] },
        { title: "Support et droits", paragraphs: ["Si vous contactez le support, Studio501 utilise l’adresse e-mail et le contenu du message uniquement pour répondre et assurer le suivi. Ces informations sont conservées pendant la durée raisonnablement nécessaire et ne sont ni vendues ni utilisées à des fins publicitaires.", "Vous pouvez demander l’accès, la rectification ou la suppression des informations transmises au support en écrivant à contact@studio501.fr."] },
        { title: "Enfants et modifications", paragraphs: ["L’application ne vise pas les enfants et ne collecte pas sciemment leurs données personnelles. Toute modification substantielle sera publiée ici avec une nouvelle date et, si nécessaire, signalée dans la fiche Microsoft Store."] },
      ],
      en: [
        { title: "Controller and scope", paragraphs: ["Publisher and controller for any support data: Candela — Studio501, France.", "Contact: contact@studio501.fr. This policy applies exclusively to Universal Converter Studio for Windows."] },
        { title: "Information processed by the app", paragraphs: ["To perform a requested conversion, the app may locally read explicitly selected files, folders and audio CD tracks, their technical properties and the required settings."], bullets: ["content, names, paths, formats, codecs, dimensions, duration and size of selected files;", "available CD-Text and titles, album or artist details entered for audio import;", "conversion settings, destination folder, queue state and history;", "a limited diagnostic log that may contain timestamps, Windows and runtime versions, file paths and error messages."] },
        { title: "Collection, transmission and sharing", paragraphs: ["The app does not transmit data to Studio501, a conversion server, an advertiser or an analytics service.", "It creates no profile and contains no built-in publishing function. Transmission occurs only if the user independently sends a file through another app or contacts support."] },
        { title: "Storage, retention and deletion", paragraphs: ["Originals and outputs remain in the chosen locations. Preferences, queue, history and diagnostics are stored locally in the app space."], bullets: ["history, completed jobs and diagnostics can be cleared in the app;", "uninstalling removes private app data according to Windows behaviour;", "originals and outputs kept in personal folders are not removed by these controls."] },
        { title: "Security", paragraphs: ["Processing remains on the PC and benefits from user-account, file-system and Windows protections. Users remain responsible for securing their device, backups and chosen folders."] },
        { title: "Third-party components", paragraphs: ["FFmpeg and ffprobe are bundled with the app and run locally to analyse and convert media. No conversion engine is downloaded during use and no file is sent to these components through a remote service."] },
        { title: "Support and your rights", paragraphs: ["If you contact support, Studio501 uses the email address and message content only to respond and follow up. This information is retained only as reasonably necessary and is not sold or used for advertising.", "You may request access, correction or deletion of support information by emailing contact@studio501.fr."] },
        { title: "Children and changes", paragraphs: ["The app is not directed at children and does not knowingly collect their personal data. Material changes will be published here with a new date and, when necessary, disclosed in the Microsoft Store listing."] },
      ],
    },
  },
  "ma-liste-de-courses": {
    lastUpdated: { fr: "21 avril 2026", en: "April 21, 2026" },
    summary: {
      fr: "L’application fonctionne localement, sans compte, publicité ni suivi publicitaire. Les listes ne sont pas envoyées à un serveur Studio501.",
      en: "The app works locally with no account, ads or advertising tracking. Shopping lists are not sent to a Studio501 server.",
    },
    sections: {
      fr: [
        { title: "Responsable", paragraphs: ["Cette politique s’applique à Ma Liste de Courses, publiée par Studio501. Contact : studio501.dev@gmail.com."] },
        { title: "Résumé simple", paragraphs: ["L’application fonctionne localement sur l’appareil. Elle ne demande pas de compte, n’intègre ni publicité ni suivi publicitaire et n’envoie pas les listes à un serveur Studio501."] },
        { title: "Données collectées", paragraphs: ["Studio501 ne collecte ni ne partage de données personnelles à des fins d’analyse, de publicité ou de profilage.", "Lorsque le système officiel Google Play In-App Updates est utilisé, des données techniques minimales peuvent être traitées par Google Play pour vérifier une mise à jour et en estimer la taille. Elles peuvent inclure des métadonnées de l’appareil, la version de l’application et les modules installés. Leur traitement relève de Google Play."] },
        { title: "Données stockées sur l’appareil", paragraphs: ["Les informations suivantes sont stockées localement afin de fournir les fonctions de l’application :"], bullets: ["listes de courses, articles et quantités ;", "états cochés ou non cochés ;", "catégories, icônes et corrections mémorisées ;", "préférences d’affichage, thème et langue."] },
        { title: "Partage manuel", paragraphs: ["Une liste est exportée ou partagée uniquement à la demande explicite de l’utilisateur via les fonctions Android. Les données partent alors vers l’application ou l’emplacement choisi par l’utilisateur, pas vers un serveur Studio501."] },
        { title: "Sauvegarde et transfert automatique", paragraphs: ["L’application est configurée pour ne pas utiliser la sauvegarde automatique Android vers le cloud. Les sauvegardes et restaurations proposées par l’application sont déclenchées et contrôlées par l’utilisateur."] },
        { title: "Conservation et suppression", paragraphs: ["Les données restent sur l’appareil jusqu’à leur modification ou suppression, la suppression des données de l’application ou sa désinstallation. Les fichiers exportés doivent être supprimés séparément depuis leur emplacement."] },
        { title: "Sécurité", paragraphs: ["Les listes restent stockées localement. Les échanges techniques nécessaires au mécanisme officiel Google Play de mise à jour sont chiffrés en transit selon le fonctionnement de Google Play."] },
        { title: "Enfants", paragraphs: ["L’application n’est pas conçue spécifiquement pour les enfants et Studio501 ne collecte pas de données personnelles par son intermédiaire."] },
        { title: "Modifications", paragraphs: ["Cette politique peut être mise à jour si les fonctionnalités changent. La date affichée en haut de la page identifie la version en vigueur."] },
      ],
      en: [
        { title: "Controller", paragraphs: ["This policy applies to Ma Liste de Courses, published by Studio501. Contact: studio501.dev@gmail.com."] },
        { title: "Plain-language summary", paragraphs: ["The app works locally on the device. It requires no account, contains no advertising or advertising tracking, and does not send shopping lists to a Studio501 server."] },
        { title: "Data collection", paragraphs: ["Studio501 does not collect or share personal data for analytics, advertising or profiling.", "When the official Google Play In-App Updates system is used, minimal technical data may be processed by Google Play to check for an update and estimate its size. This may include device metadata, app version and installed modules. Google Play controls this processing."] },
        { title: "Data stored on the device", paragraphs: ["The following information is stored locally to provide the app features:"], bullets: ["shopping lists, items and quantities;", "checked and unchecked states;", "categories, icons and remembered corrections;", "display preferences, theme and language."] },
        { title: "Manual sharing", paragraphs: ["A list is exported or shared only after an explicit user action through Android features. Data then goes to the app or location chosen by the user, not to a Studio501 server."] },
        { title: "Backup and automatic transfer", paragraphs: ["The app is configured not to use automatic Android cloud backup. Backup and restore functions provided by the app are initiated and controlled by the user."] },
        { title: "Retention and deletion", paragraphs: ["Data remains on the device until it is changed or deleted, app data is cleared, or the app is uninstalled. Exported files must be deleted separately from their saved location."] },
        { title: "Security", paragraphs: ["Lists remain stored locally. Technical exchanges required by the official Google Play update mechanism are encrypted in transit according to Google Play operation."] },
        { title: "Children", paragraphs: ["The app is not designed specifically for children and Studio501 does not collect personal data through it."] },
        { title: "Changes", paragraphs: ["This policy may be updated if features change. The date at the top identifies the current version."] },
      ],
    },
  },
  "budget-assistant": {
    lastUpdated: { fr: "2 juin 2026", en: "June 2, 2026" },
    summary: {
      fr: "Les données budgétaires sont enregistrées localement. Aucun compte, publicité, connexion bancaire ni envoi vers un serveur Studio501.",
      en: "Budget data is stored locally. No account, ads, bank connection or upload to a Studio501 server.",
    },
    sections: {
      fr: [
        { title: "Présentation", paragraphs: ["Budget Assistant est une application de suivi de budget personnel : dépenses, entrées positives, charges fixes, budgets, historique, widget Android et rapports PDF.", "L’application fonctionne localement, sans compte ni publicité, et ne transmet pas les données budgétaires à un serveur externe."] },
        { title: "Données saisies", paragraphs: ["Selon votre utilisation, les données stockées localement peuvent inclure :"], bullets: ["montants, catégories, dates, notes et libellés de dépenses ;", "charges fixes ou récurrentes, budgets mensuels et entrées positives ;", "historique et informations nécessaires au widget ;", "contenu des rapports PDF et fichiers de sauvegarde créés à votre demande."] },
        { title: "Collecte de données personnelles", paragraphs: ["Budget Assistant ne transmet pas de données personnelles au développeur. L’application ne demande ni nom, adresse e-mail, téléphone, localisation précise, contacts, photos personnelles ni informations bancaires.", "Elle ne se connecte pas aux comptes bancaires et ne permet pas d’effectuer de paiement, virement, prêt, investissement, assurance ou transaction financière."] },
        { title: "Partage des données", paragraphs: ["Studio501 ne vend, ne loue ni ne partage les données budgétaires. Elles restent sur l’appareil, sauf lorsque l’utilisateur choisit d’exporter, sauvegarder, restaurer ou partager un fichier."] },
        { title: "Sauvegardes, exports et rapports PDF", paragraphs: ["Un rapport PDF mensuel ou une sauvegarde peut contenir les informations saisies. Ces fichiers sont créés uniquement à la demande de l’utilisateur, qui choisit leur emplacement ou l’application tierce utilisée pour les partager."] },
        { title: "Permissions Android", paragraphs: ["L’application utilise uniquement les fonctions Android nécessaires, notamment le widget, les fichiers d’export et, lorsqu’elles sont activées, les notifications locales."] },
        { title: "Publicité et suivi", paragraphs: ["Budget Assistant ne contient pas de publicité, n’utilise pas de suivi publicitaire et ne vend pas de données utilisateur."] },
        { title: "Services tiers", paragraphs: ["Aucune donnée budgétaire n’est transmise à un service tiers contrôlé par Studio501. L’installation et les mises à jour peuvent faire intervenir Android ou Google Play, selon leurs propres règles de confidentialité."] },
        { title: "Sécurité", paragraphs: ["Les données sont stockées localement. Il est recommandé de protéger l’appareil et de n’envoyer les fichiers PDF ou sauvegardes qu’à des personnes ou services de confiance."] },
        { title: "Suppression", paragraphs: ["Les données peuvent être supprimées dans l’application, depuis les paramètres Android ou en désinstallant l’application. Les fichiers exportés doivent être supprimés séparément depuis l’emplacement choisi."] },
        { title: "Enfants", paragraphs: ["Budget Assistant n’est pas spécifiquement destiné aux enfants et ne cherche pas à collecter leurs données personnelles."] },
        { title: "Modifications", paragraphs: ["Cette politique peut évoluer avec l’application ou les exigences des plateformes. La date en haut de page identifie la version en vigueur."] },
        { title: "Contact", paragraphs: ["Pour toute question : studio501.dev@gmail.com ou contact@studio501.fr."] },
      ],
      en: [
        { title: "Overview", paragraphs: ["Budget Assistant is a personal budget tracking app for expenses, positive entries, fixed costs, budgets, history, an Android widget and PDF reports.", "The app works locally with no account or advertising and does not transmit budget data to an external server."] },
        { title: "Data entered in the app", paragraphs: ["Depending on use, locally stored data may include:"], bullets: ["amounts, categories, dates, notes and expense labels;", "fixed or recurring costs, monthly budgets and positive entries;", "history and information required for the widget;", "content of PDF reports and backup files created at the user’s request."] },
        { title: "Personal-data collection", paragraphs: ["Budget Assistant does not transmit personal data to the developer. The app does not ask for a name, email, phone number, precise location, contacts, personal photos or banking details.", "It does not connect to bank accounts and cannot make payments, transfers, loans, investments, insurance operations or financial transactions."] },
        { title: "Data sharing", paragraphs: ["Studio501 does not sell, rent or share budget data. It remains on the device unless the user chooses to export, back up, restore or share a file."] },
        { title: "Backups, exports and PDF reports", paragraphs: ["A monthly PDF report or backup may contain entered information. Files are created only at the user’s request, and the user chooses the storage location or third-party app used to share them."] },
        { title: "Android permissions", paragraphs: ["The app uses only the Android features required for its operation, including the widget, export files and, when enabled, local notifications."] },
        { title: "Advertising and tracking", paragraphs: ["Budget Assistant contains no ads, uses no advertising tracking and does not sell user data."] },
        { title: "Third-party services", paragraphs: ["No budget data is sent to a third-party service controlled by Studio501. Installation and updates may involve Android or Google Play under their own privacy rules."] },
        { title: "Security", paragraphs: ["Data is stored locally. Users should protect their device and send PDF files or backups only to trusted people or services."] },
        { title: "Deletion", paragraphs: ["Data can be deleted in the app, through Android settings or by uninstalling. Exported files must be deleted separately from the chosen location."] },
        { title: "Children", paragraphs: ["Budget Assistant is not specifically intended for children and does not seek to collect their personal data."] },
        { title: "Changes", paragraphs: ["This policy may change with the app or platform requirements. The date at the top identifies the current version."] },
        { title: "Contact", paragraphs: ["For questions: studio501.dev@gmail.com or contact@studio501.fr."] },
      ],
    },
  },
  myhomeassistant: {
    lastUpdated: { fr: "5 mai 2026", en: "May 5, 2026" },
    summary: {
      fr: "Les équipements, tâches et préférences sont stockés localement. Aucun compte, publicité ni serveur Studio501.",
      en: "Equipment, tasks and preferences are stored locally. No account, advertising or Studio501 server.",
    },
    sections: {
      fr: [
        { title: "Responsable", paragraphs: ["Cette politique concerne MyHomeAssistant, éditée par Studio501. Contact : studio501.dev@gmail.com ou contact@studio501.fr."] },
        { title: "Données traitées", paragraphs: ["L’application ne nécessite pas de compte et ne transmet pas les données saisies à un serveur Studio501."], bullets: ["tâches d’entretien et équipements suivis ;", "dates d’échéance, notes, descriptions et checklists ;", "historique des actions ;", "préférences locales de langue, thème, notifications et widget."] },
        { title: "Stockage local", paragraphs: ["Les données sont stockées localement sur le téléphone ou la tablette. Elles ne sont pas envoyées automatiquement à un serveur du développeur.", "Si une sauvegarde ou un export est utilisé, le fichier généré reste sous le contrôle de l’utilisateur, qui choisit où l’enregistrer ou le partager."] },
        { title: "Notifications", paragraphs: ["Les rappels sont générés localement sur l’appareil et ne nécessitent pas l’envoi des tâches à un serveur externe."] },
        { title: "Widget", paragraphs: ["Le widget affiche des tâches à venir ou en retard à partir des données locales de l’application."] },
        { title: "Mises à jour Google Play", paragraphs: ["L’application peut utiliser les services Google Play pour vérifier la disponibilité d’une mise à jour. Cette vérification est gérée par Google Play selon ses propres règles."] },
        { title: "Publicité et suivi", paragraphs: ["MyHomeAssistant ne contient pas de publicité intégrée et n’utilise pas d’outil de suivi publicitaire."] },
        { title: "Partage", paragraphs: ["Studio501 ne partage pas les données saisies. Elles quittent l’appareil uniquement après une action volontaire, par exemple lors de l’export d’une sauvegarde ou du partage d’un fichier."] },
        { title: "Sécurité", paragraphs: ["Le traitement est local. L’utilisateur reste responsable de la sécurité de son appareil, de ses sauvegardes et des fichiers exportés."] },
        { title: "Suppression", paragraphs: ["Les données peuvent être supprimées dans l’application, en réinitialisant ses données depuis Android ou en la désinstallant. Les exports doivent être supprimés séparément."] },
        { title: "Enfants", paragraphs: ["MyHomeAssistant n’est pas spécifiquement destinée aux enfants et ne propose pas de contenu ciblant les enfants."] },
        { title: "Modifications", paragraphs: ["Cette politique peut être mise à jour si l’application évolue. La date en haut de page identifie la version la plus récente."] },
      ],
      en: [
        { title: "Controller", paragraphs: ["This policy applies to MyHomeAssistant, published by Studio501. Contact: studio501.dev@gmail.com or contact@studio501.fr."] },
        { title: "Data processed", paragraphs: ["The app requires no account and does not transmit entered data to a Studio501 server."], bullets: ["home-maintenance tasks and tracked equipment;", "due dates, notes, descriptions and checklists;", "action history;", "local language, theme, notification and widget preferences."] },
        { title: "Local storage", paragraphs: ["Data is stored locally on the phone or tablet. It is not sent automatically to a developer server.", "If a backup or export is used, the generated file remains under the user’s control and the user chooses where to save or share it."] },
        { title: "Notifications", paragraphs: ["Reminders are generated locally on the device and do not require sending tasks to an external server."] },
        { title: "Widget", paragraphs: ["The widget displays upcoming or overdue tasks using local app data."] },
        { title: "Google Play updates", paragraphs: ["The app may use Google Play services to check whether an update is available. Google Play manages this check under its own rules."] },
        { title: "Advertising and tracking", paragraphs: ["MyHomeAssistant contains no integrated advertising and uses no advertising-tracking tool."] },
        { title: "Sharing", paragraphs: ["Studio501 does not share entered data. It leaves the device only after a voluntary user action, such as exporting a backup or sharing a file."] },
        { title: "Security", paragraphs: ["Processing is local. Users remain responsible for the security of their device, backups and exported files."] },
        { title: "Deletion", paragraphs: ["Data can be deleted in the app, by resetting app data through Android, or by uninstalling. Exported files must be deleted separately."] },
        { title: "Children", paragraphs: ["MyHomeAssistant is not specifically intended for children and does not provide child-directed content."] },
        { title: "Changes", paragraphs: ["This policy may be updated as the app evolves. The date at the top identifies the most recent version."] },
      ],
    },
  },
};
